"""ver2

Revision ID: c66f44692874
Revises: 577265257e64
Create Date: 2026-01-05 10:09:56.297179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c66f44692874'
down_revision: Union[str, Sequence[str], None] = '577265257e64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'favorite', 'user', ['user_id'], ['id'])
    op.add_column('picture', sa.Column('user_id', sa.String(length=36), nullable=False))
    op.create_foreign_key(None, 'picture', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'schedule', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schedule', type_='foreignkey')
    op.drop_constraint(None, 'picture', type_='foreignkey')
    op.drop_column('picture', 'user_id')
    op.drop_constraint(None, 'favorite', type_='foreignkey')
    # ### end Alembic commands ###
